document.addEventListener('DOMContentLoaded', () => {
    fetchPulseData();
});

// Global variable to store MCP data
let globalMcpData = null;
// Global variable to store pulse data for dynamic email drafting
let globalPulseData = null;

async function fetchPulseData() {
    try {
        const response = await fetch('data/latest_pulse.json');
        
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }
        
        const data = await response.json();
        globalPulseData = data; // Store for email drafting
        renderDashboard(data);
        
        // Fetch MCP Sync Metadata and store it globally for the login callback
        try {
            const mcpResponse = await fetch('data/mcp_sync.json');
            if (mcpResponse.ok) {
                globalMcpData = await mcpResponse.json();
            }
        } catch (e) {
            console.warn('Could not load MCP sync data', e);
        }
    } catch (error) {
        console.error('Error fetching pulse data:', error);
        document.getElementById('themes-container').innerHTML = 
            `<div style="color: var(--error); padding: 1rem;">Failed to load pulse data. Is latest_pulse.json generated?</div>`;
    }
}

// Build a Gmail compose URL pre-filled with the latest pulse summary
function buildGmailComposeUrl(userEmail) {
    const meta = (globalPulseData && globalPulseData.metadata) || {};
    const weekNum = meta.week_number || '--';
    const dateRange = meta.date_range || '';
    
    const to = (globalMcpData && globalMcpData.email_recipient) || 'team@example.com';
    const subject = `[Executive Brief] Noon App Pulse · W${weekNum} Metrics & Friction Points`;
    
    // Build email body from pulse data
    let body = `Noon App Pulse — Week ${weekNum} ${dateRange}\n\n`;
    body += `EXECUTIVE SUMMARY\n`;
    body += `${globalPulseData.executive_synthesis || 'No summary available.'}\n\n`;
    
    // Add top themes
    const themes = (globalPulseData.themes && globalPulseData.themes.themes) || [];
    const topThemes = themes.sort((a, b) => (b.review_count || 0) - (a.review_count || 0)).slice(0, 3);
    if (topThemes.length > 0) {
        body += `TOP THEMES\n`;
        topThemes.forEach(t => {
            const name = t.theme_name || t.name || 'Unknown';
            body += `• ${name} (${t.share || 0}% share, ${t.review_count || 0} mentions)\n`;
            if (t.representative_quote) body += `  "${t.representative_quote}"\n`;
        });
        body += `\n`;
    }
    
    // Add KPIs
    body += `KEY METRICS\n`;
    body += `• Total Reviews: ${meta.total_reviews || 'N/A'}\n`;
    body += `• Average Rating: ${meta.average_rating || 'N/A'}\n`;
    const csat = meta.csat || {};
    body += `• CSAT: Positive ${csat.positive || 0}% · Neutral ${csat.neutral || 0}% · Negative ${csat.negative || 0}%\n\n`;
    body += `---\nGenerated by AI Reviews Summarizer · MCP Workspace Sync`;
    
    return `https://mail.google.com/mail/?authuser=${encodeURIComponent(userEmail)}&view=cm&fs=1&to=${encodeURIComponent(to)}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
}

// Google Sign-In Callback
window.handleCredentialResponse = function(response) {
    try {
        const base64Url = response.credential.split('.')[1];
        const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
        const jsonPayload = decodeURIComponent(window.atob(base64).split('').map(function(c) {
            return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
        }).join(''));
        
        const decoded = JSON.parse(jsonPayload);
        const userEmail = decoded.email;
        
        // 1. Verify against explicit whitelist (if provided by backend)
        if (globalMcpData && globalMcpData.authorized_viewers) {
            const allowedViewers = globalMcpData.authorized_viewers.split(',').map(e => e.trim().toLowerCase());
            if (!allowedViewers.includes(userEmail.toLowerCase())) {
                const errEl = document.getElementById('mcp-auth-error');
                errEl.textContent = `Access Denied: ${userEmail} is not an authorized executive.`;
                errEl.classList.remove('hidden');
                return; // Stop execution, leave links hidden
            }
        }
        
        // 2. Dynamically populate the URLs with the EXACT email the user signed in with
        if (globalMcpData) {
            if (globalMcpData.document_id) {
                const docBtn = document.getElementById('btn-open-docs');
                if (docBtn) docBtn.href = `https://docs.google.com/document/d/${globalMcpData.document_id}/edit?authuser=${encodeURIComponent(userEmail)}`;
            }
            // Build Gmail compose URL dynamically from the latest pulse data
            const draftBtn = document.getElementById('btn-open-gmail');
            if (draftBtn) draftBtn.href = buildGmailComposeUrl(userEmail);
        }
        
        // 3. Hide login container, reveal actual MCP links
        document.getElementById('mcp-auth-error').classList.add('hidden');
        document.getElementById('mcp-login-container').classList.add('hidden');
        document.getElementById('mcp-links-wrapper').classList.remove('hidden');
        document.getElementById('mcp-auth-email').textContent = `Authenticated as ${userEmail}`;
        
    } catch (e) {
        console.error("Authentication decode error", e);
        const errEl = document.getElementById('mcp-auth-error');
        errEl.textContent = "Authentication failed. Please try again.";
        errEl.classList.remove('hidden');
    }
}

function renderDashboard(data) {
    const meta = data.metadata || {};
    const csat = meta.csat || { positive: 0, neutral: 0, negative: 0 };
    
    // 1. Render Metadata & KPIs
    const dateRangeStr = meta.date_range ? `(${meta.date_range})` : '';
    document.getElementById('header-week-date').textContent = `Week ${meta.week_number || '--'} ${dateRangeStr}`;
    
    animateValue('kpi-reviews-total', 0, meta.total_reviews || 0, 1000);
    document.getElementById('kpi-store-rating').textContent = meta.average_rating || '0.0';
    
    document.getElementById('kpi-csat-pos-percent').textContent = `${csat.positive}%`;
    document.getElementById('kpi-csat-neg').textContent = `Neg: ${csat.negative}%`;
    document.getElementById('kpi-csat-neu').textContent = `Neu: ${csat.neutral}%`;
    document.getElementById('kpi-csat-pos').textContent = `Pos: ${csat.positive}%`;
    
    // 2. Render Executive Synthesis
    document.getElementById('executive-synthesis-text').textContent = data.executive_synthesis || 'No executive synthesis available.';

    // 3. Render Themes & Quotes
    const themesContainer = document.getElementById('themes-container');
    const themeTemplate = document.getElementById('theme-card-template');
    themesContainer.innerHTML = '';
    
    const themesList = (data.themes && data.themes.themes) ? data.themes.themes : [];
    
    // Sort themes by review_count descending to get top 3
    const sortedThemes = themesList
        .sort((a, b) => (b.review_count || 0) - (a.review_count || 0))
        .slice(0, 3);
        
    // Extract actions from markdown_pulse
    const markdown = data.markdown_pulse || "";
    const actionRegex = /💡 \*\*Action:\*\* (.*?)(?:\n|$)/g;
    let match;
    const extractedActions = [];
    while ((match = actionRegex.exec(markdown)) !== null) {
        extractedActions.push(match[1].trim());
    }

    sortedThemes.forEach((theme, index) => {
        const clone = themeTemplate.content.cloneNode(true);
        
        const themeName = theme.theme_name || theme.name || "Unknown Theme";
        clone.querySelector('.theme-name').textContent = themeName;
        clone.querySelector('.theme-share').textContent = `${theme.share || 0}% share`;
        clone.querySelector('.theme-mentions').textContent = `${theme.review_count || 0} Mentions`;
        clone.querySelector('.theme-quote').textContent = `"${theme.representative_quote || 'No quote available.'}"`;
        clone.querySelector('.theme-bar').style.width = `${theme.share || 0}%`;
        
        themesContainer.appendChild(clone);
        
        // Save action onto the theme object for the next step
        theme.action = extractedActions[index] || "Review markdown for action details.";
    });

    // 4. Render Actions
    const actionsContainer = document.getElementById('actions-container');
    const actionTemplate = document.getElementById('action-item-template');
    actionsContainer.innerHTML = '';
    
    sortedThemes.forEach(theme => {
        if (theme.action) {
            const clone = actionTemplate.content.cloneNode(true);
            const themeName = theme.theme_name || theme.name || "Unknown Theme";
            clone.querySelector('.action-theme-name').textContent = `ACTION · ${themeName}`;
            clone.querySelector('.action-desc').textContent = theme.action;
            actionsContainer.appendChild(clone);
        }
    });

    // 5. Render Customer Voice Feed (Top Reviews)
    const voiceContainer = document.getElementById('customer-voice-container');
    const voiceTemplate = document.getElementById('review-card-template');
    
    if (voiceContainer && voiceTemplate && data.themes && data.themes.top_reviews) {
        voiceContainer.innerHTML = '';
        const topReviews = data.themes.top_reviews;
        
        topReviews.forEach(review => {
            const clone = voiceTemplate.content.cloneNode(true);
            
            // Set Rating Stars
            const rating = parseInt(review.rating) || 0;
            let starsHtml = '';
            for (let i = 0; i < 5; i++) {
                if (i < rating) {
                    starsHtml += `<span>★</span>`;
                } else {
                    starsHtml += `<span class="text-surface-container-highest">★</span>`;
                }
            }
            clone.querySelector('.review-stars').innerHTML = starsHtml;
            
            // Rating Text
            const ratingEl = clone.querySelector('.review-rating');
            ratingEl.textContent = `${rating}/5 Stars`;
            if (rating <= 2) {
                ratingEl.classList.add('text-error');
            } else if (rating === 5) {
                ratingEl.classList.add('text-tertiary');
            }
            
            // Source & Date
            if (review.source === 'google_play') {
                clone.querySelector('.review-source').textContent = 'Google Play Review';
            }
            
            if (review.date) {
                const dateObj = new Date(review.date);
                if (!isNaN(dateObj)) {
                    clone.querySelector('.review-date').textContent = dateObj.toLocaleDateString();
                } else {
                    clone.querySelector('.review-date').textContent = review.date;
                }
            }
            
            // Text
            clone.querySelector('.review-text').textContent = `"${review.text || ''}"`;
            
            // Issue Tags
            const tagsContainer = clone.querySelector('.review-tags');
            if (review.issue_tags && Array.isArray(review.issue_tags)) {
                review.issue_tags.forEach((tag, idx) => {
                    const tagSpan = document.createElement('span');
                    tagSpan.textContent = tag;
                    
                    // Assign slightly different styles for visual variety
                    if (rating <= 2 && idx === 0) {
                        tagSpan.className = "px-space-xs py-0.5 rounded bg-error-container text-on-error-container font-label-sm text-label-sm";
                    } else if (rating === 5 && idx === 0) {
                        tagSpan.className = "px-space-xs py-0.5 rounded bg-tertiary-container/60 text-on-tertiary-container font-label-sm text-label-sm";
                    } else if (idx % 2 === 0) {
                        tagSpan.className = "px-space-xs py-0.5 rounded bg-surface-container text-on-surface-variant font-label-sm text-label-sm";
                    } else {
                        tagSpan.className = "px-space-xs py-0.5 rounded bg-surface-container-low text-secondary font-label-sm text-label-sm";
                    }
                    tagsContainer.appendChild(tagSpan);
                });
            }
            
            voiceContainer.appendChild(clone);
        });
    }
}

function animateValue(id, start, end, duration) {
    if (start === end) return;
    const obj = document.getElementById(id);
    if (!obj) return;
    let startTimestamp = null;
    const step = (timestamp) => {
        if (!startTimestamp) startTimestamp = timestamp;
        const progress = Math.min((timestamp - startTimestamp) / duration, 1);
        obj.innerHTML = Math.floor(progress * (end - start) + start);
        if (progress < 1) {
            window.requestAnimationFrame(step);
        } else {
            obj.innerHTML = end; // Ensure final value is exact
        }
    };
    window.requestAnimationFrame(step);
}
